### ISSUE TITLE
Crash when import files from directory contains cyrillic symbols

### ISSUE THREAD

**Issue by YALdysse** [user-grinch/IMGEditor#10]
*Version:* baab259

App always crash when trying to import files from directory with Cyrillic symbols.
Could you, please, fix it.

**Comment by user-grinch** [comment]
Try [this](https://github.com/user-grinch/IMGEditor/actions/runs/11635887665)

**Comment by YALdysse** [comment]
@user-grinch, First of all, I want to thank you for responding to my requests.

The application no longer crashes on import, but...
