### ISSUE TITLE
GUI bugs

### ISSUE THREAD

**Issue by YALdysse** [user-grinch/IMGEditor#11]
There are some bugs in latest version (dc9f01d) of `IMGEditor`.

## 1. Broken strings in search textfield and files table

![IMGEditorApp_ArjSpPAltx](https://github.com/user-attachments/assets/bfc56c41-b79a-4064-b16d-7b9f1e4e1511)

![IMGEditorApp_XH8BlyrfjH](https://github.com/user-attachments/assets/464bcf86-5748-4074-b865-0ce1472516e2)

## 2. Search
Please, Make search case-insensitive. This will make it easier to use the app.

## 3. Hotkey for close archive
Add hotkey for close archive operation, please.

Could you, plaese, fix those.

## 4. Broken selection using mouse

If you open the archive using a keyboard shortcut, then selecting items in the table with the mouse will not work correctly. Each time you click on an item, the previous ones will remain highlighted.

**Comment by user-grinch** [comment]
Are those strings non ASCII characters?

**Comment by YALdysse** [comment]
> Are those strings non ASCII characters?

It is not ASCII.

**Comment by user-grinch** [comment]
The UI doesn't support non ASCII characters atm. Got exam tomorrow. Will fix in a day or two.

**Comment by YALdysse** [comment]
> Got exam tomorrow.

I wish you a successful exam.


> Will fix in a day or two.

Thank you so much.

**Comment by user-grinch** [comment]
Check the latest commit

**Comment by user-grinch** [comment]
Support for non ASCII characters probably isn't that worth considering IMG format doesn't support it either.

**Comment by YALdysse** [comment]
> Support for non ASCII characters probably isn't that worth considering IMG format doesn't support it either.

I agree. What about other bugs.

**Comment by user-grinch** [comment]
> > Support for non ASCII characters probably isn't that worth considering IMG format doesn't support it either.
> 
> I agree. What about other bugs ?

Check now

**Comment by YALdysse** [comment]
Thank you very much for taking the time to correct the errors. Everything is working perfectly.
