### ISSUE TITLE
Missing textures bug

### ISSUE THREAD

**Issue by YALdysse** [user-grinch/IMGEditor#12]
**Game:** *GTA: Vice City*
**IMGEditor:** *e8d4386*

### Description

Textures imported via `Grinch_'s IMG Editor` are not displayed in the game.
Could you, please, fix it.

### Steps to reproduce

1. Open archive using hotkey
1. Delete all radar files (`radar00.txd`, `radar01.txd` ...)
1. Import all radar files using hotkey
1. Save the archive using hotkey

### Screenshots

![reVC_4nc7LLoMaV](https://github.com/user-attachments/assets/2db5a696-96e1-460f-996c-3214dd6381ce)

**Comment by user-grinch** [comment]
Seems to work here though.

**Comment by YALdysse** [comment]
> Seems to work here though.

I don't understand what you mean.

**Comment by user-grinch** [comment]
> > Seems to work here though.
> 
> I don't understand what you mean.

Working when I tried it

**Comment by YALdysse** [comment]
Here's a video of me replacing the weapon icons. After replacing them with Grinch_'s IMG Editor, the icons do not appear in the game.
[video](https://drive.google.com/file/d/1-PwU1LxUGHIsq3VKqWRIjPwIAUpv0i9y/view?usp=sharing)

Am I doing something wrong?

However, there is no such problem in IMG Tool 1.3.

**Comment by user-grinch** [comment]
> Here's a video of me replacing the weapon icons. After replacing them with Grinch_'s IMG Editor, the icons do not appear in the game. [video](https://drive.google.com/file/d/1-PwU1LxUGHIsq3VKqWRIjPwIAUpv0i9y/view?usp=sharing)
> 
> Am I doing something wrong?
> 
> However, there is no such problem in IMG Tool 1.3.

I just tried again and it seems to work

**Comment by YALdysse** [comment]
Please, let's do one last check. 
I am asking you to do this because I have never been able to successfully replace the weapon icons, although I have made many attempts.
I still think it's a bug in IMG Editor. 


Here is the [sniper.txd](https://drive.google.com/file/d/1VZJGKqLox7F6JgOv39bvQJqjRMZkf44k/view?usp=sharing) file (or [directory](https://drive.google.com/drive/folders/178TIDDA4BSaJmuk_APFOAcZW8Ltarx53?usp=sharing) with txd's).

Replace the `sniper.txd` (from the link above) file in `gta3.img` for GTA: Vice City and send a screenshot of the result in the game.
This test will show me exactly whether it is my problem or not.
Please.

**Comment by user-grinch** [comment]
Found the issue. Will fix in a few days.

**Comment by YALdysse** [comment]
> Found the issue. Will fix in a few days.

Thank you so much!

**Comment by user-grinch** [comment]
The latest commit should fix your issue.

**Comment by YALdysse** [comment]
The issue has been fixed. Thanks.
