### ISSUE TITLE
Crash on open img archive

### ISSUE THREAD

**Issue by YALdysse** [user-grinch/IMGEditor#17]
The latest version (c37c1a5) crashes on opening img archive v1 GTA: VC.

**Comment by user-grinch** [comment]
Send me the archive

**Comment by YALdysse** [comment]
It crashes with any archive.
[img](https://drive.google.com/drive/folders/1JlhuKtkaUB37_lv1r1zg8Oss068GM5EL?usp=sharing)

**Comment by Crowtheris** [comment]
The latest version still refuses to open any .img for me either, I tried with the last version and it works but the update prompt doesn't let me use the program.
[Here's my .img file in case.](https://mega.nz/file/4IkSRJrD#7Z5OCqDMbVqtgk4qwc3M8GcchGoG51jaK8R09xfIreM)
