### ISSUE TITLE
Why is IMGFactory not specified in the authorship references? I see a clear similarity

### ISSUE THREAD

**Issue by SaH4PoK** [user-grinch/IMGEditor#4]
![light](https://github.com/user-grinch/IMGEditor/assets/33376413/5b06be69-b117-4de1-b928-adce29e189e1)
![2NhlUGV](https://github.com/user-grinch/IMGEditor/assets/33376413/2d1d65ce-abd8-4f88-bc5b-4bac6d2a18a5)

**Comment by user-grinch** [comment]
Two projects aren't connected in any way shape or form. The code is not forked/taken from their sources. There's no point to mention them.
