### ISSUE TITLE
"Export selected" doesn't exract files into directory

### ISSUE THREAD

**Issue by YALdysse** [user-grinch/IMGEditor#8]
Hi. I want to say, that `IMGEditor` awesome software.

There is the issue in IMGEditor v0.5. The one doesn't export files in directory, that contains cyrillic symbols.
Could you please fix this. Thank you.

**Comment by user-grinch** [comment]
Waiting for feedback [here](https://github.com/user-grinch/IMGEditor/actions/runs/11617110168#artifacts)

**Comment by YALdysse** [comment]
> Waiting for feedback [here](https://github.com/user-grinch/IMGEditor/actions/runs/11617110168/artifacts/2129756678)

Yeah. Functiion "Extract selected" works properly now. Thanks.
