### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by YALdysse** [user-grinch/IMGEditor#9]
I have a few suggestions that will improve the usability of your program:
1. The "Export" and "Delete" commands in the context menu are executed only for one selected file, not for many.
2. Add hotkeys for menu items and buttons. For example, you could open an IMG-archive with Ctrl+O, delete selected items with Delete key, etc.

Please, implement these features.

**Comment by user-grinch** [comment]
Completed

**Comment by YALdysse** [comment]
Completed ? There is not any commits in last time.

**Comment by YALdysse** [comment]
Thanks for the commit, but there are new bugs in last one.

### Scroll on table bug
1. Open program
2. Open IMG archive using hotkey
3. Now scroll items on table doesn't work

### IMG archve version lable bug
1. Open program
2. Open IMG archve
3. Select "Save As..." using hotkey and close the window without saving
4. Label with IMG version shows unknown value
